### ISSUE TITLE
Error after designating a directions file/setting interactive to false

### ISSUE THREAD

**Issue by agwilber** [lofar-astron/factor#169]
I have modified the order of the facets in the factor_directions.txt file that was created when factor was run with interactive = T. When I set the path to this direction file in my parset and set interactive = F, I get an immediate error about directions.py ... (seems as though it's trying to re-build directions?)

INFO - factor - Setting up directions...
INFO - factor:directions - Reading directions file: /beegfs/sttf310/data/P165-57-newdata/factor/fullband/factor_directions.txt
Traceback (most recent call last):
  File "/home/lofar/local/src/factor_master/bin/runfactor", line 70, in <module>
    reset_operations)
  File "/home/lofar/local/src/factor_master/factor/process.py", line 73, in run
    test_run, reset_directions, reset_operations)
  File "/home/lofar/local/src/factor_master/factor/process.py", line 576, in _set_up_directions
    max_radius_deg=max_radius_deg, dry_run=dry_run)
  File "/home/lofar/local/src/factor_master/factor/process.py", line 833, in _initialize_directions
    target_radius_arcmin=target_radius_arcmin, beam_ratio=beam_ratio)
  File "/home/lofar/local/src/factor_master/factor/directions.py", line 760, in thiessen
    for n in range(len(points_all) - nouter)]
  File "/home/lofar/local/src/factor_master/factor/directions.py", line 1139, in _thiessen_poly
    triangles = _find_triangles_for_vertex(tri, n)
  File "/home/lofar/local/src/factor_master/factor/directions.py", line 1071, in _find_triangles_for_vertex
    sorted_triangles = [triangles[0]]
IndexError: index out of bounds

**Comment by darafferty** [comment]
Did you check your directions file for problems (duplicate entries, etc.)?

**Comment by agwilber** [comment]
Yes this was the problem! I found a duplicate entry. Thanks!
