### ISSUE TITLE
dppp failed and checkfactor problem in CEP3

### ISSUE THREAD

**Issue by botteon** [lofar-astron/factor#176]
Hi,
I've started running factor on CEP3 this week and I have two issues:

1) checkfactor doesn't work, I have this message:

```
botteon@lof003:~$ checkfactor parsets/factor1.parset 
Traceback (most recent call last):
  File "/home/rafferty/LOFAR/factor/bin/checkfactor", line 20, in <module>
    from factor import check_progress
  File "/home/rafferty/LOFAR/factor/factor/check_progress.py", line 20, in <module>
    from lofarpipe.support.data_map import DataMap
ImportError: No module named lofarpipe.support.data_map
```
note that I also have this warning:

```
botteon@lof003:~$ use LofIm
LofIm Sun-build appears to be successful
Could not find daily lofar init script /opt/cep/LofIm/daily/Sun/lofar/lofarinit.csh
```

2) I received a "dppp failed" error on the first facet (outlierpeel source). I tried also a run excluding the outlier source and starting from the first facet, but I got the same error. The last 100 rows of the two runs (starting with the outlier and with facet123) follow.

```
botteon@lof003:/data/scratch/botteon/factor_runs/factor1/logs/outlierpeel$ tail -100 facet_patch_13.out.log
0%....10....20....30....40....50....60....70....80....90....100%

2017-01-08 12:30:11 DEBUG   node.lof003.executable_args.L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk7.ms: /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin/DPPP stdout:  copying info and subtables ...
Finished preparing output MS
MSReader
  input MS:       /data/scratch/botteon/factor_runs/factor1/chunks/Band_158.30MHz/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk7.ms
  band            0
  startchan:      0  (0)
  nchan:          40  (0)
  ncorrelations:  4
  nbaselines:     1891
  ntimes:         596
  time interval:  4.02653
  DATA column:    SUBTRACTED_DATA_ALL
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
PhaseShift shift.
  phasecenter:    [212.829062917deg,52.1970050556deg]
Predict add.
  sourcedb:           /data/scratch/botteon/factor_runs/factor1/results/outlierpeel/facet_patch_13/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal.wsclean_low2-model.make_sourcedb_cal_facet_sources
   number of patches: 32
   number of sources: 32
  apply beam:         false
  operation:          add
  threads:            6
ApplyCal add.applycal.
  parmdb:         /data/scratch/botteon/factor_runs/factor1/chunks/Band_158.30MHz/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk7.ms/instrument_directionindependent
  correction:     gain
    Ampl/Phase:   true
  update weights: false
  sigmaMMSE:      0
  invert:         false
  timeSlotsPerParmUpdate: 500
Averager avg.
  freqstep:       40  timestep:       1
  minpoints:      1
  minperc:        0
MSWriter msout.
  output MS:      /data/scratch/botteon/factor_runs/factor1/results/outlierpeel/facet_patch_13/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk7.shift_cal
  nchan:          1
  ncorrelations:  4
  nbaselines:     1891
  ntimes:         596
  time interval:  4.02653
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  Compressed:     no

Processing 596 time slots ...
Finishing processing ...

NaN/infinite data flagged in reader
===================================

Percentage of flagged visibilities detected per correlation:
  [0,0,0,0] out of 45081440 visibilities   [0%, 0%, 0%, 0%]
0 missing time slots were inserted






Total NDPPP time      65.61 real       126.5 user           2 system
   49.2% MSReader
    2.6% PhaseShift shift.
   34.1% Predict add.
    4.4% Averager avg.
    9.5% MSWriter msout.

2017-01-08 12:30:11 WARNING node.lof003.executable_args.L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk7.ms: /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin/DPPP stderr: 
0%....10....20....30....40....50....60....70....80....90....100%

2017-01-08 12:30:13 DEBUG   outlierpeel_facet_patch_13.executable_args: Results for job 178 submitted by ('10.144.5.105', 57835)
2017-01-08 12:30:13 INFO    node.lof003.executable_args: Total time 68.0750s; user time: 126.5959s; system time: 2.3041s
2017-01-08 12:30:13 DEBUG   node.lof003.executable_args: Start time was 1483878545.8986s; end time was 1483878613.9737s
2017-01-08 12:30:14 DEBUG   outlierpeel_facet_patch_13.executable_args: 
2017-01-08 12:30:14 WARNING outlierpeel_facet_patch_13.executable_args: 
2017-01-08 12:30:14 INFO    outlierpeel_facet_patch_13.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 178 10.144.5.105 52660
2017-01-08 12:30:14 DEBUG   outlierpeel_facet_patch_13.executable_args: compute.dispatch results job 178: job_duration: 68.3274629116, returncode: 0 
2017-01-08 12:30:14 DEBUG   outlierpeel_facet_patch_13.executable_args: Results for job 179 submitted by ('10.144.5.105', 57836)
2017-01-08 12:30:14 INFO    node.lof003.executable_args: Total time 68.0738s; user time: 132.6883s; system time: 2.5362s
2017-01-08 12:30:14 DEBUG   node.lof003.executable_args: Start time was 1483878546.4970s; end time was 1483878614.5711s
2017-01-08 12:30:14 DEBUG   outlierpeel_facet_patch_13.executable_args: 
2017-01-08 12:30:14 WARNING outlierpeel_facet_patch_13.executable_args: 
2017-01-08 12:30:14 INFO    outlierpeel_facet_patch_13.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 179 10.144.5.105 52660
2017-01-08 12:30:14 DEBUG   outlierpeel_facet_patch_13.executable_args: compute.dispatch results job 179: job_duration: 68.3044438362, returncode: 0 
2017-01-08 12:30:15 DEBUG   outlierpeel_facet_patch_13.executable_args: Adding node_logging_information
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13.executable_args: A job has failed with returncode 1 and error_tolerance is not set. Bailing out!
2017-01-08 12:30:15 WARNING outlierpeel_facet_patch_13.executable_args: Note: recipe outputs are not complete
2017-01-08 12:30:15 WARNING outlierpeel_facet_patch_13.executable_args: recipe executable_args completed with errors
2017-01-08 12:30:15 WARNING outlierpeel_facet_patch_13: dppp reports failure (using executable_args recipe)
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: *******************************************
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: Failed pipeline run: facet_patch_13
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: Detailed exception information:
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: dppp failed
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: *******************************************
2017-01-08 12:30:15 ERROR   outlierpeel_facet_patch_13: LOFAR Pipeline finished unsuccesfully.
2017-01-08 12:30:15 WARNING outlierpeel_facet_patch_13: recipe outlierpeel_facet_patch_13 completed with errors
```
and
```
botteon@lof003:~$ tail -100 /data/scratch/botteon/factor_runs/factor1/logs/facetselfcal/facet_patch_123.out.log 
2017-01-08 13:32:14 INFO    facetselfcal_facet_patch_123.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 177 10.144.5.105 57023
2017-01-08 13:32:14 DEBUG   facetselfcal_facet_patch_123.executable_args: compute.dispatch results job 177: job_duration: 64.4237101078, returncode: 0 
2017-01-08 13:32:16 DEBUG   node.lof003.executable_args.L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk8.ms: /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin/DPPP stdout:  copying info and subtables ...
Finished preparing output MS
MSReader
  input MS:       /data/scratch/botteon/factor_runs/factor1/chunks/Band_158.30MHz/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk8.ms
  band            0
  startchan:      0  (0)
  nchan:          40  (0)
  ncorrelations:  4
  nbaselines:     1891
  ntimes:         596
  time interval:  4.02653
  DATA column:    SUBTRACTED_DATA_ALL
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
PhaseShift shift.
  phasecenter:    [206.373881667deg,49.7659653611deg]
Predict add.
  sourcedb:           /data/scratch/botteon/factor_runs/factor1/results/facetselfcal/facet_patch_123/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal.wsclean_low2-model.make_sourcedb_cal_facet_sources
   number of patches: 47
   number of sources: 47
  apply beam:         false
  operation:          add
  threads:            6
ApplyCal add.applycal.
  parmdb:         /data/scratch/botteon/factor_runs/factor1/chunks/Band_158.30MHz/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk8.ms/instrument_directionindependent
  correction:     gain
    Ampl/Phase:   true
  update weights: false
  sigmaMMSE:      0
  invert:         false
  timeSlotsPerParmUpdate: 500
Averager avg.
  freqstep:       40  timestep:       1
  minpoints:      1
  minperc:        0
MSWriter msout.
  output MS:      /data/scratch/botteon/factor_runs/factor1/results/facetselfcal/facet_patch_123/L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk8.shift_cal
  nchan:          1
  ncorrelations:  4
  nbaselines:     1891
  ntimes:         596
  time interval:  4.02653
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  Compressed:     no

Processing 596 time slots ...
Finishing processing ...

NaN/infinite data flagged in reader
===================================

Percentage of flagged visibilities detected per correlation:
  [0,0,0,0] out of 45081440 visibilities   [0%, 0%, 0%, 0%]
0 missing time slots were inserted






Total NDPPP time       55.1 real      133.24 user        1.94 system
   40.6% MSReader
    2.7% PhaseShift shift.
   41.1% Predict add.
    5.3% Averager avg.
    9.9% MSWriter msout.

2017-01-08 13:32:16 WARNING node.lof003.executable_args.L230423_SB000_uv.dppp_1248F906Et_158MHz.pre-cal_chunk8.ms: /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin/DPPP stderr: 
0%....10....20....30....40....50....60....70....80....90....100%

2017-01-08 13:32:16 DEBUG   facetselfcal_facet_patch_123.executable_args: Results for job 178 submitted by ('10.144.5.105', 48550)
2017-01-08 13:32:16 DEBUG   facetselfcal_facet_patch_123.executable_args: 
2017-01-08 13:32:16 WARNING facetselfcal_facet_patch_123.executable_args: 
2017-01-08 13:32:16 INFO    facetselfcal_facet_patch_123.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 178 10.144.5.105 57023
2017-01-08 13:32:16 DEBUG   facetselfcal_facet_patch_123.executable_args: compute.dispatch results job 178: job_duration: 61.2232689857, returncode: 0 
2017-01-08 13:32:16 INFO    node.lof003.executable_args: Total time 61.0653s; user time: 134.7644s; system time: 2.0841s
2017-01-08 13:32:16 DEBUG   node.lof003.executable_args: Start time was 1483882275.0983s; end time was 1483882336.1638s
2017-01-08 13:32:18 DEBUG   facetselfcal_facet_patch_123.executable_args: Results for job 179 submitted by ('10.144.5.105', 48551)
2017-01-08 13:32:18 INFO    node.lof003.executable_args: Total time 58.0619s; user time: 133.3243s; system time: 2.2201s
2017-01-08 13:32:18 DEBUG   node.lof003.executable_args: Start time was 1483882280.8604s; end time was 1483882338.9225s
2017-01-08 13:32:18 DEBUG   facetselfcal_facet_patch_123.executable_args: 
2017-01-08 13:32:18 WARNING facetselfcal_facet_patch_123.executable_args: 
2017-01-08 13:32:18 INFO    facetselfcal_facet_patch_123.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 179 10.144.5.105 57023
2017-01-08 13:32:18 DEBUG   facetselfcal_facet_patch_123.executable_args: compute.dispatch results job 179: job_duration: 58.2588369846, returncode: 0 
2017-01-08 13:32:19 DEBUG   facetselfcal_facet_patch_123.executable_args: Adding node_logging_information
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123.executable_args: A job has failed with returncode 1 and error_tolerance is not set. Bailing out!
2017-01-08 13:32:20 WARNING facetselfcal_facet_patch_123.executable_args: Note: recipe outputs are not complete
2017-01-08 13:32:20 WARNING facetselfcal_facet_patch_123.executable_args: recipe executable_args completed with errors
2017-01-08 13:32:20 WARNING facetselfcal_facet_patch_123: dppp reports failure (using executable_args recipe)
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: *******************************************
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: Failed pipeline run: facet_patch_123
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: Detailed exception information:
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: dppp failed
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: *******************************************
2017-01-08 13:32:20 ERROR   facetselfcal_facet_patch_123: LOFAR Pipeline finished unsuccesfully.
2017-01-08 13:32:20 WARNING facetselfcal_facet_patch_123: recipe facetselfcal_facet_patch_123 completed with errors
```

Note that my previous runs with the same parset didn't fail on Leiden paracluster.

**Comment by darafferty** [comment]
The first problem is due to a problem with the LOFAR software on CEP3. I expect this will be fixed within a day or two. For now, you can do `use LofIm Thu` after `source ~rafferty/init_factor`and it should work (at least until this Thursday).

For the second problem, the log excerpts that you posted don't contain the original error message from DPPP. Try searching backwards for "error" until you find it (for DPPP errors in particular, you can also try to search for "Backtrace").

**Comment by botteon** [comment]
Hi, with the provided command I can use checkfactor. Thank you.

For the second issue I have this error:

`2017-01-08 13:25:01 ERROR   facetselfcal_facet_patch_123.executable_args: Remote process python /opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py ['/data/scratch/botteon/factor_runs/factor1/chunks/Band_152.44MHz/L230423_SB000_uv.dppp_1248F906Et_152MHz.pre-cal_chunk1.ms', '/opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin/DPPP', [], {'msin.datacolumn': 'SUBTRACTED_DATA_ALL', 'shift.type': 'phaseshifter', 'add.applycal.parmdb': '/data/scratch/botteon/factor_runs/factor1/chunks/Band_152.44MHz/L230423_SB000_uv.dppp_1248F906Et_152MHz.pre-cal_chunk1.ms/instrument_directionindependent', 'numthreads': '6', 'msout.writefullresflag': 'False', 'add.type': 'predict', 'avg.freqstep': '40', 'shift.phasecenter': '[206.373881667deg, 49.7659653611deg]', 'add.operation': 'add', 'msout.overwrite': 'True', 'steps': '[shift,add,avg]', 'msout': '/data/scratch/botteon/factor_runs/factor1/results/facetselfcal/facet_patch_123/L230423_SB000_uv.dppp_1248F906Et_152MHz.pre-cal_chunk1.shift_cal', 'avg.timestep': '1', 'add.sourcedb': '/data/scratch/botteon/factor_runs/factor1/results/facetselfcal/facet_patch_123/L230423_SB000_uv.dppp_1248F906Et_152MHz.pre-cal.wsclean_low2-model.make_sourcedb_cal_facet_sources', 'avg.type': 'squash', 'msin': '/data/scratch/botteon/factor_runs/factor1/chunks/Band_152.44MHz/L230423_SB000_uv.dppp_1248F906Et_152MHz.pre-cal_chunk1.ms'}, '/data/scratch/botteon/factor_runs/factor1/results/facetselfcal/facet_patch_123', True, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'lofar', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'LOFARDATAROOT': '/opt/lofar/data', 'OMP_NUM_THREADS': '8', 'PYTHONPATH': '/home/rafferty/.local/lib/python:/home/rafferty/LOFAR/wcsaxes/lib/python/:/home/rafferty/LOFAR/LSMTool:/home/rafferty/LOFAR/factor:/home/rafferty/.local/lib/python:/home/rafferty/LOFAR/wcsaxes/lib/python/:/home/rafferty/LOFAR/LSMTool:/home/rafferty/LOFAR/factor:/home/rafferty/.local/lib/python:/home/rafferty/LOFAR/wcsaxes/lib/python/:/home/rafferty/LOFAR/LSMTool:/home/rafferty/LOFAR/factor:/opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages:/opt/cep/pyrap/current/lib/python2.7/site-packages:/opt/cep/lofar/external/lib/python/site-packages:/opt/cep/pythonlibs/lib/python/site-packages', 'LOFARROOT': '/opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt', 'PATH': '/home/rafferty/LOFAR/LSMTool/bin:/home/rafferty/LOFAR/factor/bin:/home/rafferty/LOFAR/LSMTool/bin:/home/rafferty/LOFAR/factor/bin:/home/rafferty/LOFAR/LSMTool/bin:/home/rafferty/LOFAR/factor/bin:/opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/sbin:/opt/cep/lofar/lofar_versions/LOFAR-Release-2_19_0/lofar_build/install/gnu_opt/bin:/opt/cep/casarest/current/bin:/opt/cep/casacore/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/cep/scripts:/opt/cep/saoimage/bin:/opt/cep/pythonlibs/bin:/opt/cep/WSClean/bin:/opt/cep/Casa/bin', 'LD_LIBRARY_PATH': '/home/rafferty/.local/lib:/opt/cep/wcslib/lib:/opt/cep/pyrap/current/lib:/opt/cep/casarest/current/lib:/opt/cep/casacore/current/lib:.'}] failed on localhost`

for all the Band_152.44MHz/*chunk##.ms. I deleted chunck Band_152.44MHz and started factor again, now it seems to work. 
Factor was interrupted in the first run during the creation of the chunks, and this might have caused the problem.

I close this issue, i might re-open it if checkfactor won't work in the next days. Thank you.
