### ISSUE TITLE
TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by fvitello** [lofar-astron/factor#230]
Hi, i am running factor that fails with the following logs:

> DEBUG - factor:facet_patch_224 - Calibrator is 0.00310144973491 deg across
> DEBUG - factor:facet_patch_224 - Target timewidth for selfcal is 120.0 s
> DEBUG - factor:facet_patch_224 - Target bandwidth for selfcal is 2.0 MHz
> DEBUG - factor:facet_patch_224 - Using averaging steps of 20 channels and 15 time slots for selfcal
> DEBUG - factor:facet_patch_224 - Facet image before padding is 2215 x 2215 pixels (0.922916666667 x 0.922916666667 deg)
> DEBUG - factor:facet_patch_224 - Target timewidth for facet imaging is 21.6656483094 s
> DEBUG - factor:facet_patch_224 - Target bandwidth for facet imaging is 0.255163158748 MHz
> DEBUG - factor:facet_patch_224 - Using averaging steps of 4 channels and 3 time slots for facet imaging
> WARNING - factor:facet_patch_224 - Could not find source components for the calibrator in one or more of the direction-independent sky models. Using largest allowable solution intervals
> DEBUG - factor:facet_patch_224 - Preaveraging in frequency and time will be done
> DEBUG - factor:facet_patch_224 - Using solution intervals of 1 (fast) and 150 (slow) time slots
> QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
> INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_224)
> ERROR - factor:scheduler - Operation facetselfcal failed due to an error (direction: facet_patch_224)
> Traceback (most recent call last):
>   File "/opt/factor/bin/runfactor", line 4, in <module>
>     __import__('pkg_resources').run_script('FACTOR==1.4', 'runfactor')
>   File "/opt/pip/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/opt/pip/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
>     exec(code, namespace, namespace)
>   File "/opt/factor-1.4/lib/python2.7/site-packages/FACTOR-1.4-py2.7.egg/EGG-INFO/scripts/runfactor", line 72, in <module>
>     reset_operations, stop_after=options.stop_after)
>   File "/opt/factor/lib/python2.7/site-packages/FACTOR-1.4-py2.7.egg/factor/process.py", line 187, in run
>     scheduler.run(ops)
>   File "/opt/factor/lib/python2.7/site-packages/FACTOR-1.4-py2.7.egg/factor/lib/scheduler.py", line 314, in run
>     pool.join()
>   File "/opt/factor/lib/python2.7/site-packages/FACTOR-1.4-py2.7.egg/factor/lib/scheduler.py", line 310, in run
>     process.wait(30)
>   File "/usr/lib64/python2.7/multiprocessing/pool.py", line 543, in wait
>     self._cond.wait(timeout)
>   File "/usr/lib64/python2.7/threading.py", line 362, in wait
>     _sleep(delay)
> TypeError: 'int' object is not callable

could you please help me to solve the issue?

**Comment by darafferty** [comment]
I have not seen this issue before. It might be related to this one: https://bugs.python.org/issue23395, but I'm not sure (and if it is, I don't know how to fix it). If you have write access to the` /opt/factor/lib/python2.7/site-packages/FACTOR-1.4-py2.7.egg/factor/lib/scheduler.py` file, you can try removing the try/except block (lines 305 through 313) where the problem occurs. This block tries to catch keyboard interrupts and propagate them, but is not really necessary.
