### ISSUE TITLE
KeyError: max_cpus_per_node

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#57]
(this is for the reimage branch)

Continue processing (y/n)? y
INFO - factor:directions - Reading directions file: /p3600/rvweeren/factor_directions.txt
INFO - factor:facet_patch_539 - Using sky model file /home/rvweeren/software/prefactor/skymodels/3C295.test.bbsmodel for selfcal/peeling
INFO - factor:directions - Adjusting facets to avoid sources...
INFO - factor - Processing 1 direction(s) in Group 1
Traceback (most recent call last):
  File "/usr/local/bin/runfactor", line 5, in <module>
    pkg_resources.run_script('FACTOR==1.0', 'runfactor')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/EGG-INFO/scripts/runfactor", line 70, in <module>
    reset_operations)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/process.py", line 177, in run
    ops = [FacetSelfcal(parset, bands, d) for d in direction_group]
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/operations/facet_ops.py", line 46, in **init**
    name='FacetSelfcal')
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/lib/operation.py", line 144, in **init**
    + 'max_per_node = {0}\n'.format(self.cfg_dict['max_cpus_per_node'])
KeyError: 'max_cpus_per_node'

**Comment by rvweeren** [comment]
Ok, confirmed this is fixed.
