### ISSUE TITLE
unexpected keyword argument 'imging_only'

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#60]
Another error, again the reimage branch with peeling.

maybe a typo "imging_only" vs "imaging_only" ?

Continue processing (y/n)? y
INFO - factor:directions - Reading directions file: /p3600/rvweeren/factor_directions.txt
INFO - factor:facet_patch_539 - Using sky model file /home/rvweeren/software/prefactor/skymodels/3C295.test.bbsmodel for selfcal/peeling
INFO - factor:directions - Adjusting facets to avoid sources...
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
INFO - factor:scheduler - <-- Operation facetpeel started (direction: facet_patch_539)
log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.
INFO - factor:scheduler - --> Operation facetpeel completed (direction: facet_patch_539)
Traceback (most recent call last):
  File "/usr/local/bin/runfactor", line 5, in <module>
    pkg_resources.run_script('FACTOR==1.0', 'runfactor')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/EGG-INFO/scripts/runfactor", line 70, in <module>
    reset_operations)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/process.py", line 117, in run
    op = FacetPeelImage(parset, bands, d)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/operations/facet_ops.py", line 394, in **init**
    self.direction.set_imcal_parameters(parset, bands, imging_only=True)
TypeError: set_imcal_parameters() got an unexpected keyword argument 'imging_only'

**Comment by rvweeren** [comment]
Confirmed it is a typo-bug, changing "imging_only" to "imaging_only" in facet_ops.py fixed the problem.

**Comment by darafferty** [comment]
Yep, a copy-and-paste error. Should be fixed now.
