### ISSUE TITLE
Direction object has no attribute 'diff_models_field_mapfile'

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#62]
And more errors (reimage branch)

-More--(20%)INFO - factor:scheduler - --> Operation facetpeelimage completed (direction: facet_patch_539)
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
INFO - factor:scheduler - <-- Operation facetsub started (direction: facet_patch_539)
log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.
INFO - factor:scheduler - --> Operation facetsub completed (direction: facet_patch_539)
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 396, in _handle_results
    cache[job]._set(i, obj)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 563, in _set
    self._callback(self._value)
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/lib/scheduler.py", line 114, in result_callback
    this_op.finalize()
  File "/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/operations/facet_ops.py", line 222, in finalize
    self.direction.cleanup_mapfiles = [self.direction.diff_models_field_mapfile]
AttributeError: 'Direction' object has no attribute 'diff_models_field_mapfile'

**Comment by darafferty** [comment]
Added a check for this, so it should work now.
