### ISSUE TITLE
multinode with pbs

### ISSUE THREAD

**Issue by wndywllms** [lofar-astron/factor#79]
I'm trying to use factor with more than one node on the herts cluster. Like Hamburg we have pbs running and setting  `clusterdesc_file = PBS` does seem to work up to the point where it attempts to run dppp. It seems to have trouble parsing the parsetfile as an argument for the special `dppp_nodescript`

The pipeline log contains:

```
2016-05-03 11:11:19 INFO    facetselfcal_s18: Running task: dppp
2016-05-03 11:11:19 INFO    facetselfcal_s18.executable_args: recipe executable_args started
2016-05-03 11:11:19 INFO    facetselfcal_s18.executable_args: Starting /soft/lofar-220216/bin/DPPP run
2016-05-03 11:11:19 DEBUG   facetselfcal_s18.executable_args: Pipeline start time: 2016-05-03T10:11:19
2016-05-03 11:11:19 INFO    facetselfcal_s18.executable_args: Limiting to 16 simultaneous jobs/node
2016-05-03 11:11:19 DEBUG   facetselfcal_s18.executable_args: Job dispatcher at 192.168.2.135:51055
2016-05-03 11:11:19 DEBUG   facetselfcal_s18.executable_args: Dispatching command to node131 with ssh
2016-05-03 11:11:19 ERROR   facetselfcal_s18.executable_args: Failed to run remote process None (sequence item 5: expected string, NoneType found)
Traceback (most recent call last):
  File "/soft/lofar-220216/lib64/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 280, in dispatch
    arguments = [id, jobhost, jobport]
  File "/soft/lofar-220216/lib64/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 102, in run_remote_command
    return run_via_ssh(logger, host, command, env, arguments)
  File "/soft/lofar-220216/lib64/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 182, in run_via_ssh
    ssh_cmd.append('"' + " ".join(commandstring) + '"')
TypeError: sequence item 5: expected string, NoneType found
```

I can make it run using the normal executable_args call for dppp.

**Comment by darafferty** [comment]
Good that the pbs mode seems to be working for you. 

Regarding the DPPP error, do you have the dppp_scratch.py script installed in the recipes/nodes directory of your LOFAR installation? It has to be there to be picked up properly.

**Comment by wndywllms** [comment]
Thanks David, I didn't have the dppp_scratch.py in the right place. Now it is running correctly.

I actually  thought factor would know about this dppp_scratch without having to put it in the LOFAR installation - could this not be done by including it in the recipes directory in the pipeline.cfg file factor creates with
recipe_directories = [%(pythonpath)s/lofarpipe/recipes,%(factorroot)s/pipeline/recipes]
task_files = [%(factorroot)s/pipeline/tasks.cfg]

**Comment by AHorneffer** [comment]
> I actually thought factor would know about this dppp_scratch without having to put it in the LOFAR installation - could this not be done by including it in the recipes directory in the pipeline.cfg file factor creates with
> recipe_directories = [%(pythonpath)s/lofarpipe/recipes,%(factorroot)s/pipeline/recipes]
> task_files = [%(factorroot)s/pipeline/tasks.cfg]

I didn't think about that before (there is no use for that on "my" machines), but that should indeed work. Did you give it a try?

**Comment by wndywllms** [comment]
Yes, tried it now and it works (after removing the dppp_scratch.py from the LOFAR install location).

I also pushed my change to the reimage brach (I didn't realize I actually have write access on this repo (not true for prefactor so I got a bit confused))

**Comment by AHorneffer** [comment]
I guess we can close this now.  (If not, then please re-open.)
